version: '3.8'

services:
  wallet-finance-web:
    build: .
    depends_on:
      - postgres-wallet
      - broker
    command: [ "./wallet-finance-web" ]
    environment:
      APP_NAME: wallet-finance
      APP_ENV: development
      GIN_MODE: release
      APP_DEBUG: true
      APP_VERSION: v2
      HTTP_PORT: 8080
      DEV_SHOW_QUERY: true
      DB_PREFIX: boiler_
      DB_CONNECTION: postgres
      DB_HOST: postgres-wallet
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_DATABASE: cms
      LOG_PATH: ./logs/
      ALLOW_ORIGINS: '*'
      ALLOW_METHODS: POST,GET,PUT,DELETE
      ALLOW_HEADERS: x-api-key
      KAFKA_SECURITY_PROTOCOL: PLAIN
      KAFKA_USERNAME: none
      KAFKA_PASSWORD: none
      KAFKA_BROKERS: broker:9092
      KAFKA_GROUP_ID: dev
      KAFKA_TOPIC_TRANSACTION: transaction
    ports:
      - "8080:8080"
    restart: on-failure

  wallet-finance-worker:
    build: .
    depends_on:
      - wallet-finance-web
      - postgres-wallet
      - broker
    command: [ "./wallet-finance-worker" ]
    environment:
      APP_NAME: wallet-finance
      APP_ENV: development
      GIN_MODE: release
      APP_DEBUG: true
      APP_VERSION: v2
      HTTP_PORT: 8080
      DEV_SHOW_QUERY: true
      DB_PREFIX: boiler_
      DB_CONNECTION: postgres
      DB_HOST: postgres-wallet
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_DATABASE: cms
      LOG_PATH: ./logs/
      ALLOW_ORIGINS: '*'
      ALLOW_METHODS: POST,GET,PUT,DELETE
      ALLOW_HEADERS: x-api-key
      KAFKA_SECURITY_PROTOCOL: PLAIN
      KAFKA_USERNAME: none
      KAFKA_PASSWORD: none
      KAFKA_BROKERS: broker:9092
      KAFKA_GROUP_ID: dev
      KAFKA_TOPIC_TRANSACTION: transaction
    restart: on-failure

  postgres-wallet:
    image: postgres:14.12
    container_name: postgres-wallet
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cms
    ports:
      - "5432:5432"

  broker:
    image: apache/kafka:3.8.0
    hostname: broker
    container_name: broker
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT_HOST://localhost:9092,PLAINTEXT://broker:19092'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@broker:29093'
      KAFKA_LISTENERS: 'CONTROLLER://:29093,PLAINTEXT_HOST://:9092,PLAINTEXT://:19092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      CLUSTER_ID: 'dev'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

